# Generated by Django 4.2.30 on 2026-04-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skin_images/'),
        ),
    ]
